# Generated by Django 4.2 on 2023-07-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_type',
        ),
    ]
